version: '2'
services:

  ### Mysql container
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
      
    environment:
      MYSQL_ROOT_PASSWORD: 241021@Vinay
      MYSQL_DATABASE: expense-app
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes